openapi: 3.1.0
info:
  title: Authentication API
  version: 1.0.0

paths:
  /auth-code:
    post:
      summary: Generate and send auth_code by email
      operationId: generateAndSendAuthCode
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateAndSendAuthCodeRequest'
      responses:
        "201":
          description: Auth_code is generated and sent to user email
  /auth:
    post:
      summary: Authenticate a user
      description: Authenticates a user with an email and auth_code
      operationId: auth
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        "200":
          description: User authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

components:
  schemas:

    GenerateAndSendAuthCodeRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          example: user@example.com

    AuthRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        authCode:
          type: string
          minimum: 1000
          maximum: 9999

    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string