openapi: 3.1.0
info:
  title: Authentication API
  version: 1.0.0

paths:
  /auth-code:
    post:
      summary: Generate and send auth_code by email
      operationId: generateAndSendAuthCode
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateAndSendAuthCodeRequest'
      responses:
        "201":
          description: Auth_code is generated and sent to user email
  /login:
    post:
      summary: Authenticate a user
      description: Authenticates a user with an email and password
      operationId: login
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: User authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

components:
  schemas:

    GenerateAndSendAuthCodeRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          example: user@example.com

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          minLength: 8
          example: mySecurePass123

    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string