openapi: 3.1.0
info:
  title: Car API
  version: 1.0.0

paths:
  /users/{userId}/cars:
    post:
      summary: Create a new car
      description: Creates a new car for the user
      operationId: create
      tags:
        - cars
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCarRequest'
      responses:
        '201':
          description: Car successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarDetailsResponse'
    get:
      summary: Get car by user id
      description: Searches cars by user id
      operationId: findByUserId
      tags:
        - cars
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Car successfully created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CarDetailsResponse'
  /users/{userId}/cars/{carId}:
    put:
      summary: Update car details
      description: Updates user car details
      operationId: update
      tags:
        - cars
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: carId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCarRequest'
      responses:
        '200':
          description: Car successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarDetailsResponse'
    delete:
      summary: Delete car details
      description: Deletes user car details
      operationId: delete
      tags:
        - cars
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: carId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Car successfully deleted

components:
  schemas:
    CreateCarRequest:
      type: object
      properties:
        make:
          type: string
          minLength: 1
          maxLength: 255
        model:
          type: string
          minLength: 1
          maxLength: 255
        year:
          type: integer
          minimum: 1900
        engine:
          type: string
          maxLength: 255
        fuelType:
          type: string
          maxLength: 255
      required:
        - make
        - model

    UpdateCarRequest:
      type: object
      properties:
        make:
          type: string
          minLength: 1
          maxLength: 255
        model:
          type: string
          minLength: 1
          maxLength: 255
        year:
          type: integer
          minimum: 1900
        engine:
          type: string
          maxLength: 255
        fuelType:
          type: string
          maxLength: 255
      required:
        - make
        - model

    CarDetailsResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        make:
          type: string
        model:
          type: string
        year:
          type: integer
          min: 1900
        engine:
          type: string
        fuelType:
          type: string
        createdAt:
          type: string
          format: date-time